---
title: "Exploratory Data Analysis"
author: "Kristen Shaver (kes3648)"
date: '2020-03-16'
output:
  html_document: default
  pdf_document: default
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, fig.align = "center", warning = F, message = F,
tidy=TRUE, tidy.opts=list(width.cutoff=60), R.options=list(max.print=100))
```

## Introduction

The first data set chosen was "GDP". This data set contains information on the Gross Domestic Product (in billions) for the United States by quarter since 1947. The second data set chosen was "Unemployment". This data set contains information on the unemployment rate (percentage) in the United States by year since 1948. The third data set chosen was "Presidents". This data set contains a list of United States preisdent by year since 1947. The final data set chosen was "Income". This data set contains information on the per capita income (in US dollars) in the United States since 1929. These data sets were obtained by searching on the "Dataset Search" feature on Google. I chose these data sets because I felt that they were all tied into the United States economy. I expect there to be a direct correlation between unemployment rate and per capita income and GDP. I also expect there to be smaller trends for GDP, unemployment rate, and per capita income within different presidencies.

```{R}
library(dplyr)
library(tidyverse)
GDP<-read.csv("GDP.csv")%>%glimpse()
Unemployment<-read.csv("Unemployment.csv")%>%glimpse()
Presidents<-read.csv("Presidents.csv")%>%glimpse()
Income<-read.csv("Income.csv")%>%glimpse()
```

## Tidying: Rearranging Wide/Long

These data sets were already tidy, so I decided to untidy and re-tidy them. First, I wanted to combine two of the datasets, GDP and Income, so I altered their Date variables to only include their year (to match the other two data sets). GDP included a GDP value per quarter, so each year had 4 GDP values. I decided to change this into an average yearly GDP, so I used the summarize() function to convert to an average yearly GDP. I then joined these two data sets into "GDPIncome1". After this, I altered the other two data sets, Presidents and Unemployment. In the Presidents data set, the Year variable was a numeric variable, so I changed it to be a character variable. In Unemployment, the Date and Rate varaibles were renamed to "Year" and "Unemploy_Rate" in order to match the other data sets and to be more descriptive. Finally, I was ready to un-tidy my data sets, so I used pivot_longer() on GDPIncome1. This took both of the monetary variables, avgGDP_billions and per_capita_income, and put them in one column, and their numeric values in another column by year. After that, I joined this un-tidy data set to my other two data sets, Presidents and Unemployment (explanation on joining in next section), into "Combined". I next decided to re-tidy this combined data set, so I used pivot_wider() to separate out the average GDP values from the per capita income values into their own columns.

```{R}
GDP1<-GDP%>%separate(Date,4,into=c("Year"))%>%group_by(Year)%>%summarize(avgGDP_billions=mean(GDP_billions))
Income1<-Income%>%separate(Date,4,into = c("Year"))
GDPIncome1<-GDP1%>%full_join(Income1)

Presidents<-Presidents%>%mutate(Year=as.character(Year))
Unemployment<-Unemployment%>%rename("Year"="Date")%>%mutate(Year=as.character(Year))%>%rename("Unemploy_Rate"="Rate")

Combined<-GDPIncome1%>%pivot_longer(cols=(2:3))%>%inner_join(Presidents)%>%inner_join(Unemployment)
Combined1<-Combined%>%pivot_wider(names_from = "name",values_from = "value")%>%mutate(avgGDP=avgGDP_billions*1000000000)%>%select(cols=-c(4))

```

## Joining/Merging

I used inner_join() to join my data sets because I had extra observations in some of my data sets that didn't correspond to observations in the other data sets and I didn't want to include NAs in my combined data set. The only cases that were dropped were from years that extended beyond the year range of the other data sets. I do not expect any problems with this.

```{R}
Combined<-GDPIncome1%>%pivot_longer(cols=(2:3))%>%inner_join(Presidents)%>%inner_join(Unemployment)
Combined2<-Combined%>%pivot_wider(names_from = "name",values_from = "value")%>%mutate(avgGDP=avgGDP_billions*1000000000)%>%select(cols=-c(4))
```

## Wrangling

(1) It was found that Eisenhower was in the lowest percentile for unemployment rate in 1953, meaning that during this year he had the lowest unemployment rate compared to the other presidents throughout the years. (2) For observations with unemployment rate over 5, the mean unemployment rate was 6.657778, the mean per capita income was 18600.73, and the mean GDP was 6202519061111. (3) The overall standard deviation of unemployment rate was 1.604746, 16736.13 for per capita income, and 6331037392727 for average GDP. (4) In the data set, there were 72 different years, 13 different presidents, 39 different unemployment rate values, 72 different per capita income values, and 72 different average GDP values. (5) The minimum value was 2.9 for unemployment rate, 1415 for per capita income, and 272475250000 for average GDP. (6) The maximum value was 10.4 for unemployment rate, 56621 for per capita income, and 21427103250000 for GDP. (7) The two numeric variables with the highest correlation are avergae GDP and per capita income.

```{R}
#1
Combined2%>%mutate(`Unemploy_pctile` = ntile(Unemploy_Rate,100))%>%arrange(Unemploy_pctile)
#2
Combined2%>%filter(Unemploy_Rate>5)%>%summarize_if(is.numeric,mean)
#3
Combined2%>%summarize_if(is.numeric,sd)
#4
Combined2%>%summarize_all(n_distinct)
#5
Combined2%>%summarize_if(is.numeric,min)
#6
Combined2%>%summarize_if(is.numeric,max)
#7
Combined2%>%select_if(is.numeric)%>%cor
```

(8) The mean unemployment rate per President was calculated. Reagan was found to have the highest mean unemployment rate, and Truman had the lowest mean unemployment rate. (9) The per capita income variable was converted into a categorical variable by configuring three categories, high, medium, and low, and assiging each observation to one of these categories. The mean per capita income for the high level income category was 41813.10, 15860.96 for medium level income, and 2620.36 for the low income level. (10) Trump had the highest average GDP of the high level income category. Nixon had the highest average GDP of the low level income category. Clinton had the highest average GDP of the medium level income category.

```{R}
#8
Combined2%>%group_by(President)%>%summarize(mean(Unemploy_Rate))
#9
Combined2%>%mutate(PCincome_cat = case_when(per_capita_income>30000 ~ "high",5000<=per_capita_income & per_capita_income<=30000 ~ "med",per_capita_income<5000 ~ "low"))%>%group_by(PCincome_cat)%>%summarize(mean(per_capita_income))
Combined3<-Combined2%>%mutate(PCincome_cat = case_when(per_capita_income>30000 ~ "high",5000<=per_capita_income & per_capita_income<=30000 ~ "med",per_capita_income<5000 ~ "low"))
#10
Combined3%>%group_by(PCincome_cat,President)%>%summarize(mean(avgGDP))
```

## Visualizing

(1) The correlation heat map displays the relationships between the three different numeric variables. The lighter the color of the square, the lesser the correlation between variables. The darker the color, the greater the correlation between variables. The two variables with the greatest correlation were per capita income and average GDP. This is intuitive because as more goods and services are produced, the more money these good and service providers are making, which would eventually increase the income made per individual. The two variables with the least correlation were unemployment rate and average GDP. This was surprising, as I thought that unemployment rate would have a greater impact on the total value of goods and services produced in the country (GDP).

```{R}
#1
df1<-Combined3%>%na.omit%>%select_if(is.numeric)
cor(df1)
ComCor<-cor(df1)%>%as.data.frame%>%rownames_to_column%>%pivot_longer(-1,names_to="name",values_to="correlation")
ComCor%>%ggplot(aes(rowname,name,fill=correlation))+  geom_tile()+  scale_fill_gradient2(low="blue",mid="white",high="red")+geom_text(aes(label=round(correlation,3)),color = "black", size = 4)+theme(axis.text.x = element_text(hjust = 1))+coord_fixed()+labs(title = "Correlation Heat Map")
```

(2) This graph displays the average GDP as a function of per capita income and provides information on who was president at the time of each observation. As the per capita income increases, so does the average GDP. As seen in the above correlation heat map, these two variables have the highest correlation, and when plotted on a graph, display an almost perfectly straight line, consistent with the correlation value provided above. In addition, as the observations progress in the upward direction, the presidents during each observation are approximately in chronological order. 

```{R}
#2
Combined3%>%ggplot(aes(per_capita_income,avgGDP,color=President))+geom_point()+theme_minimal()+labs(title = "Per Capita Income vs Average GDP")+scale_y_continuous(breaks=seq(0, 20000000000000, 2500000000000))+xlab("Per Capita Income")+ylab("Average GDP")
```

(3) This graph depicts the mean unemployment rate per president and also provides information on the proportion of per capita income categories during each presdient's observations. Not many trends were extrapolated from this graph, but it was noted that most presidents that had a lower unemployment rate also fell into the low income category.

```{R}
#3
Combined3%>%ggplot(aes(President,Unemploy_Rate,fill=PCincome_cat))+geom_bar(stat = "Summary",fun.y="mean")+ggtitle("Average Unemployment Rate per President")+theme(axis.text.x = element_text(angle=30,hjust = 1))+ylab("Mean Unemployment Rate")+scale_fill_brewer(palette = "Set3",name="Per Capita Income Category")
```

## Dimensionality Reduction

PC1 accounts for 68.063% of the variance, PC2 accounts for 31.864% of the variance, and PC3 accounts for 0.073% of the variance. A high score on PC1 represents lower monetary circulation during that year in the United States economy. A low score on PC1 represented higher monetary circulation during that year in the United States economy. PC2 represents unempoyment vs monetary circulation. A high score on PC2 represents high unemployment rate and low monetary circulation. A low score on PC2 represents low unemployment rate and high monetary circulation. The years 1948, 1952, and 1953 were high on PC1. The years 2017, 2018, and 2019 were low on PC1. The years 1982, 1983, and 2010 were high on PC2. The years 1953, 2018, and 2018 were low on PC2.

```{R}
Combined4<-Combined3
Com_nums<-Combined4%>%select_if(is.numeric)%>%scale
rownames(Com_nums)<-Combined4$Year
Com_pca<-princomp(Com_nums)
names(Com_pca)
summary(Com_pca, loadings=T)

Comdf<-data.frame(PC1=Com_pca$scores[,1], PC2=Com_pca$scores[,2])
ggplot(Comdf,aes(PC1, PC2))+geom_point()

Year<-Combined4$Year
Com_pca$scores%>%as.data.frame%>%cbind(Year,.)%>%top_n(3,Comp.1)
Com_pca$scores%>%as.data.frame%>%cbind(Year,.)%>%top_n(3,wt=desc(Comp.1))
Com_pca$scores%>%as.data.frame%>%cbind(Year,.)%>%top_n(3,wt=Comp.2)
Com_pca$scores%>%as.data.frame%>%cbind(Year,.)%>%top_n(3,wt=desc(Comp.2))
```











